name: "Github Action for annotating in grafana"
author: "Ilya Shevchenko <id.shev@yandex.ru>"
branding:
  icon: "edit-3"
  color: "blue"
inputs:
  dashboard:
    description: "Dashboard UID"
    required: false
    default: "7CzMl5t4k"
  pod:
    description: "Pod name"
    required: true
  text:
    description: "Text to set"
    required: true
  tags:
    description: "Tags to set to annotation"
    default: "[]"
    required: false
  annotations-url:
    description: "Grafana annotation URL"
    required: false
    default: http://localhost:3000/api/annotations
runs:
  using: "composite"
  steps:
    - name: Sanitize tags
      shell: bash
      run: echo TAGS=$TAGS | sed -e 's/"/\\"/g' >> $GITHUB_ENV

    - name: Echo command
      shell: bash
      run: >
        echo kubectl exec -it ${{ inputs.pod }} --container grafana -- /bin/bash -c "
        wget -qS -O- --header 'Accept: application/json' --header 'Content-Type: application/json' 
        --post-data '{\"dashboardUID\":\"${{ inputs.dashboard }}\", \"text\":\"${{ inputs.text }}\", \"tags\":${TAGS}}'
        '${{ inputs.annotations-url }}' "

    - name: Push annotation
      shell: bash
      run: >
        kubectl exec -it ${{ inputs.pod }} --container grafana -- /bin/bash -c "
        wget -qS -O- --header 'Accept: application/json' --header 'Content-Type: application/json' 
        --post-data '{\"dashboardUID\":\"${{ inputs.dashboard }}\", \"text\":\"${{ inputs.text }}\", \"tags\":${TAGS}}'
        '${{ inputs.annotations-url }}' "
