name: "Github Action for annotating in grafana"
author: "Ilya Shevchenko <id.shev@yandex.ru>"
branding:
  icon: "edit-3"
  color: "blue"
inputs:
  dashboard:
    description: "Dashboard UID"
    required: false
    default: "7CzMl5t4k"
  dashboard1:
    description: "Dashboard1 UID"
    required: false
    default: "SaEJlEwVk"
  text:
    description: "Text to set"
    required: true
  tags:
    description: "Tags to set to annotation"
    default: "[]"
    required: false
  annotations-url:
    description: "Grafana annotation URL"
    required: false
    default: http://localhost:3000/api/annotations
description: "Github Action for annotating in grafana"
runs:
  using: "composite"
  steps:
    - name: Sanitize tags
      shell: bash
      run: echo TAGS='${{ inputs.tags }}' >> $GITHUB_ENV

    - name: Push annotation
      shell: bash
      run: >
        kubectl exec -it 
        `kubectl get pods -l "app.kubernetes.io/name=grafana" -o jsonpath="{.items[0].metadata.name}"`
        --container grafana -- /bin/bash -c "
        echo '{\"dashboardUID\":\"${{ inputs.dashboard }}\", \"text\":\"${{ inputs.text }}\", \"tags\":${TAGS}}';
        wget -qS -O- --header 'Accept: application/json' --header 'Content-Type: application/json'
        --post-data '{\"dashboardUID\":\"${{ inputs.dashboard }}\", \"text\":\"${{ inputs.text }}\", \"tags\":${TAGS}}'
        '${{ inputs.annotations-url }}'; "
