name: Build SDK workload flow

on:
  workflow_call:
    inputs:
      language:
        description: 'SDK language or language+variant'
        required: true
        type: string
      build_timeout:
        description: 'Timeout to build image'
        default: '3m'
        required: false
        type: string
    secrets:
      KUBE_CONFIG:
        required: true
      DOCKER_REPO:
        required: true
      DOCKER_FOLDER:
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build-workload-image:
    name: build-${{ inputs.language }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      
      - run: cd ${{ inputs.language }}

      - name: Login into docker
        run: >
          echo "${{ secrets.DOCKER_PASSWORD }}" | base64 -d |
          docker login ${{ secrets.DOCKER_REPO }}
          -u ${{ secrets.DOCKER_USERNAME }}
          --password-stdin

      - name: Build ${{ inputs.language }} image
        run: >
          docker build 
          -t ${{ secrets.DOCKER_REPO }}/${{ secrets.DOCKER_FOLDER }}/${{ inputs.language }}:latest
          -t ${{ secrets.DOCKER_REPO }}/${{ secrets.DOCKER_FOLDER }}/${{ inputs.language }}:${{ github.head_ref }}.${{ github.sha }}
          .

      - name: Push image with all tags
        run: >
          docker push -a
          {{ secrets.DOCKER_REPO }}/{{ secrets.DOCKER_FOLDER }}/${{ inputs.language }}