name: Build SDK workload flow

on:
  workflow_call:
    inputs:
      language_id:
        description: "SDK language or language+variant"
        required: true
        type: string
      build_timeout:
        description: "Timeout to build image"
        default: "3m"
        required: false
        type: string
      workload_path:
        description: "Workload folder to build docker image from"
        required: true
        type: string
      context:
        description: "Path to docker build context - cwd is workload_path"
        default: "."
        type: string
      options:
        description: "String with additional options, such as --build-arg and others from https://docs.docker.com/engine/reference/commandline/build/#options"
        default: ""
        type: string

    secrets:
      DOCKER_REPO:
        required: true
      DOCKER_FOLDER:
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build-workload-image:
    name: build-${{ inputs.language_id }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login into docker
        run: >
          docker --version;
          echo "${{ secrets.DOCKER_PASSWORD }}" | base64 -d |
          docker login ${{ secrets.DOCKER_REPO }}
          -u ${{ secrets.DOCKER_USERNAME }}
          --password-stdin

      - name: Build ${{ inputs.language_id }} image
        working-directory: ${{ inputs.workload_path }}
        run: >
          docker build 
          -t ${{ secrets.DOCKER_REPO }}/${{ secrets.DOCKER_FOLDER }}/${{ inputs.language_id }}:latest
          -t ${{ secrets.DOCKER_REPO }}/${{ secrets.DOCKER_FOLDER }}/${{ inputs.language_id }}:gh-${{ github.sha }}
          ${{ inputs.options }}
          ${{ inputs.context }}

      - name: Push image with all tags
        run: >
          docker image push ${{ secrets.DOCKER_REPO }}/${{ secrets.DOCKER_FOLDER }}/${{ inputs.language_id }}:latest;
          docker image push ${{ secrets.DOCKER_REPO }}/${{ secrets.DOCKER_FOLDER }}/${{ inputs.language_id }}:gh-${{ github.sha }}
