name: Full SLO test workflow

on:
  workflow_call:
    inputs:
      language:
        description: "SDK language or language+variant"
        required: true
        type: string
      workload-path:
        description: "Workload folder to build docker image from"
        required: true
        type: string
    secrets:
      KUBE_CONFIG:
        required: true
      DOCKER_REPO:
        required: true
      DOCKER_FOLDER:
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      AWS_CREDENTIALS:
        required: true
      AWS_CONFIG:
        required: true
      s3-endpoint:
        required: true

concurrency: slo

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: create-cluster
        uses: ./.github/actions/cluster
        with:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          command: apply

  build-workload:
    uses: ./.github/workflows/build-workload.yml
    secrets:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
      DOCKER_FOLDER: ${{ secrets.DOCKER_FOLDER }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    with:
      language: ${{ inputs.language }}
      workload-path: ${{ inputs.workload-path }}

  create-tables:
    needs: [create-cluster, build-workload]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: mkdir $HOME/.kube; echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config

      - name: Run workload
        uses: ./.github/actions/workload
        with:
          language: "${{ inputs.language }}"
          command: "create"
          timeout: "20s"

  run-workload:
    needs: [create-cluster, create-tables, build-workload]
    uses: ./.github/workflows/run-slo.yml
    secrets: inherit
    with:
      language: ${{ inputs.language }}

  check-results:
    needs: [run-workload]
    uses: ./.github/workflows/check-prometheus.yml
    secrets:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
    with:
      test_start: ${{ needs.run-workload.outputs.test_start }}
      test_end: ${{ needs.run-workload.outputs.test_end }}
      test_start_iso: ${{ needs.run-workload.outputs.test_start_iso }}
      test_end_iso: ${{ needs.run-workload.outputs.test_end_iso }}

  cleanup-tables:
    needs: [run-workload]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: mkdir $HOME/.kube; echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config

      - name: Run workload
        uses: ./.github/actions/workload
        with:
          language: "${{ inputs.language }}"
          command: "cleanup"
          timeout: "20s"

  grafana-screenshot:
    needs: [run-workload]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - run: mkdir $HOME/.kube; echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config

      - name: Create screenshot
        uses: ./.github/actions/grafana-screenshot
        id: screenshot
        with:
          time_from: ${{ needs.run-workload.outputs.test_start }}
          time_to: ${{ needs.run-workload.outputs.test_end }}
          AWS_CREDENTIALS: ${{ secrets.AWS_CREDENTIALS }}
          AWS_CONFIG: ${{ secrets.AWS_CONFIG }}
          s3-endpoint: ${{ secrets.S3_ENDPOINT }}
          image-folder: "ydb-slo-results/"
          image-prefix: "${{ inputs.language }}"

      - name: Log image URL
        run: echo "${{ steps.screenshot.outputs.picture-url}}"

      - name: Add comment to PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: slo-image
          message: |
            Here are results of SLO test :volcano: :

            [Grafana Dashboard](${{ vars.INGRESS_ADDRESS }}/d/${{ vars.GRAFANA_DASHBOARD }}?orgId=1&from=${{ needs.run-workload.outputs.test_start }}&to=${{ needs.run-workload.outputs.test_end }})

            ![SLO-${{ inputs.language }}](${{ steps.screenshot.outputs.picture-url}})

  # delete-cluster:
  #   needs: [grafana-screenshot]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         ref: ${{ github.ref }}
  #     - name: create-cluster
  #       uses: ./.github/actions/cluster
  #       with:
  #         KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
  #         command: delete
