name: "Take screenshot in grafana"
author: "Ilya Shevchenko <id.shev@yandex.ru>"
inputs:
  dashboard:
    description: "Dashboard UID"
    default: "7CzMl5t4k"
  width:
    default: 1500
  height:
    default: 1100
  time:
    description: "How much time from now to be captured"
    default: "5m"
  grafana-host:
    description: "Grafana host"
    default: "http://grafana"
  AWS_ACCESS_KEY_ID:
    required: true
  AWS_SECRET_ACCESS_KEY:
    required: true
  AWS_REGION:
    required: true
  s3-endpoint:
    required: true
  s3-bucket:
    required: true
  image-folder:
    default: "ydb-slo-results/"
  image-prefix:
    required: true

outputs:
  picture-url:
    description: "Uploaded picture url"
    value: ${{ steps.upload.outputs.url }}

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.AWS_REGION }}

    - name: Get dashboard picture from grafana
      shell: bash
      run: >
        kubectl run -it --image=busybox --rm tablet-freezer --restart=Never -- sh -c "
        wget -q -O- 'http://grafana/render/d/7CzMl5t4k/slo?orgId=1&from=now-5m&to=now&width=1500&height=1100&tz=Europe%2FIstanbul&kiosk=tv' 
        | base64" | base64 --decode > pic.png

    - name: Upload image to the bucket
      id: upload
      shell: bash
      run: |
        export PICTURE_NAME=${{ inputs.image-prefix }}-`date -I seconds`.png;
        aws s3 --endpoint-url=${{ inputs.s3-endpoint }} cp ./pic.png "s3://${{ inputs.image-folder }}${PICTURE_NAME}";
        echo "url=${inputs.s3-endpoint}/${inputs.image-folder}${PICTURE_NAME}" >> $GITHUB_OUTPUT
